// Package root — re-exports the public API surface.

export type {
  AffectedDetails,
  ArchitectureModel,
  BriefDetails,
  CalleesData,
  CapabilityState,
  CodeIntelResult,
  CodeLocation,
  CodePosition,
  CodeProvider,
  CodeProviderState,
  CodeResult,
  CodeSymbol,
  ConfidenceMode,
  ContextDetails,
  DependencyEdge,
  DisambiguationCandidate,
  ExportData,
  HealthDetails,
  ImpactDetails,
  ImportData,
  InspectDetails,
  ModuleInfo,
  NodeAtData,
  OutlineData,
  ResolveDetails,
  ResolvedTargetData,
  ResolvedTargetGroupData,
  SearchDetails,
  SemanticProvider,
  SemanticProvider as SemanticSubstrate,
  SourceRange,
  StructuralProvider,
  StructuralProvider as StructuralSubstrate,
  StructuralResult,
  TargetOutcome,
  TestSurfaceDetails,
} from "./api.ts";
export {
  buildArchitectureModel,
  findModuleForPath,
  getCodeProvider,
  getDependencies,
  getDependents,
  normalizePath,
} from "./api.ts";
