import type { Model, ModelThinkingLevel, Usage } from "@earendil-works/pi-ai";
import type {
  AgentRunDiagnostics,
  AgentRunProviderAuthority,
} from "@mrclrchtr/supi-agent-runtime/api";
import type { LocalReviewAuditStore } from "./audit/local-review-audit-store.ts";
import type { ReviewThinkingLevel } from "./thinking.ts";
import type { ReviewWorkspaceCleanupWarning } from "./workspace/review-workspace.ts";

/** A full Git commit id after target resolution. */
export type CommitId = string;

/** Public Review Target input. Omit it, or use an empty object, for the current filesystem. */
export type ReviewTargetSpec =
  | { workingTree?: never; committed?: never }
  | { workingTree: WorkingTreeReviewTarget; committed?: never }
  | { workingTree?: never; committed: CommittedReviewTarget };

/** Target source for the frozen current filesystem. */
export interface WorkingTreeReviewTarget {
  /** Optional before commit syntax. The Review Engine resolves it once. */
  from?: string;
}

/** Target source for exact committed Git state. */
export interface CommittedReviewTarget {
  /** Optional before commit syntax. The Review Engine resolves it once. */
  from?: string;
  /** Optional after commit syntax. It defaults to HEAD. */
  to?: string;
}

/** Exact target state used by the Review Engine after endpoint resolution. */
export interface ResolvedReviewTarget {
  /** Exact before commit or the filesystem freeze base. */
  fromCommit?: CommitId;
  /** Exact captured HEAD for a filesystem target, or exact committed after state. */
  toCommit: CommitId;
  /** True when the after state is the frozen current filesystem. */
  includeUncommittedChanges: boolean;
}

export interface DiffStats {
  files: number;
  additions: number;
  deletions: number;
}

/** One changed path with Git status and per-file line statistics. */
export interface ReviewChange {
  /** Git name-status token, such as `M`, `A`, `D`, or `R100`. */
  status: string;
  /** Path on the target's after side, or the deleted path when no after-side path exists. */
  path: string;
  /** Before-side path for a detected rename or copy. */
  previousPath?: string;
  /** Null for binary changes. */
  additions: number | null;
  /** Null for binary changes. */
  deletions: number | null;
}

/** Concrete target metadata and diff identity resolved before reviewer execution. */
export interface ReviewSnapshot {
  /** Canonical worktree root retained only inside the Review Engine. */
  repositoryRoot: string;
  requestedTarget: ReviewTargetSpec;
  target: ResolvedReviewTarget;
  title: string;
  changes: ReviewChange[];
  /** SHA-256 of the exact canonical target patch bytes. */
  diffHash: string;
  stats: DiffStats;
}

export type ReviewSnapshotSummary = Omit<ReviewSnapshot, "repositoryRoot">;

/** Post-materialization proof that a Review Workspace matches its pinned target. */
export interface ReviewWorkspaceReceipt {
  status: "verified";
  fromCommit?: CommitId;
  toCommit: CommitId;
  includeUncommittedChanges: boolean;
  expectedWorkspaceHead: CommitId;
  observedWorkspaceHead: CommitId;
  expectedDiffHash: string;
  observedDiffHash: string;
  changedPathCount: number;
}

/** Opaque identifier for an opt-in local reviewer replay artifact. */
export interface ReviewAuditReference {
  artifactId: string;
  expiresAt: string;
}

/** Required evidence view and finding policy for one Review Task. */
export type ReviewMode = "change" | "state";

/** Caller-identified authoritative issue or repository document for Review Criteria. */
export interface CriteriaSource {
  /** Identifier such as an issue reference, URL, or repository-relative path. */
  reference: string;
  /** Caller summary used before the reviewer retrieves the source itself. */
  summary: string;
}

/** One independent caller-defined review objective. */
export interface ReviewTask {
  id: string;
  instructions: string;
  /** Required evidence view and finding policy. */
  mode: ReviewMode;
  criteriaSources?: CriteriaSource[];
}

/** Optional batch-level path focus that remains separate from the Review Target. */
export interface ReviewScope {
  /** Repository-relative paths that focus every task without restricting inspection. */
  paths?: string[];
}

/** Semantic input shared with the reviewer tasks in one run. */
export interface ReviewInput {
  sharedContext?: string;
  tasks: ReviewTask[];
}

/** Advisory review input generated by the optional lightweight Planner. */
export type PlannerDraft = ReviewInput;

export type FindingImpact = "low" | "medium" | "high";
export type FindingEffort = "small" | "medium" | "large";
export type TaskVerdict = "pass" | "pass_with_findings" | "issues" | "incomplete";

/** A reviewer's structured statement about Review Criteria Source coverage. */
export type CriteriaCoverage = { status: "complete" } | { status: "incomplete"; reason: string };

/** Machine-derived count of all findings, including their acceptance and impact split. */
export interface FindingCounts {
  total: number;
  blocking: number;
  nonBlocking: number;
  byImpact: Record<FindingImpact, number>;
}

export interface ReviewLocation {
  path: string;
  startLine: number;
  endLine: number;
}

/** One structured issue submitted by a reviewer task. */
export interface ReviewFinding {
  title: string;
  description: string;
  blocksAcceptance: boolean;
  impact: FindingImpact;
  effort: FindingEffort;
  confidence: number;
  location?: ReviewLocation;
}

/** Fixed Review Engine-owned submission grammar. */
export interface ReviewSubmission {
  summary: string;
  findings: ReviewFinding[];
  criteriaCoverage: CriteriaCoverage;
}

export interface NormalizedReviewSubmission extends ReviewSubmission {
  verdict: TaskVerdict;
  findingCounts: FindingCounts;
}

/** Provenance for one finite same-session Submission Recovery chain. */
export interface SubmissionRecovery {
  readonly status: "succeeded" | "declined" | "exhausted";
  readonly attempts: readonly SubmissionRecoveryAttempt[];
  readonly declineReason?: string;
}

/** One model's bounded Submission Recovery Turn. */
export interface SubmissionRecoveryAttempt {
  readonly modelId: string;
  readonly outcome:
    | "submitted"
    | "declined"
    | "no-terminal-output"
    | "model-switch-failed"
    | "provider-failed";
  readonly usage?: Usage;
}

export type ReviewModelSelection = import("@mrclrchtr/supi-core/model-selection").ModelSelection;

export type ChildStage = "planner" | "reviewer";

/** Runtime diagnostics retained under review's existing failure vocabulary. */
export type ChildFailureDiagnostics = AgentRunDiagnostics;

export type ChildFailureCode =
  | "session-creation-failed"
  | "prompt-rejected"
  | "missing-structured-output"
  | "unexpected-runner-failure";

export type ChildFailedResult =
  | { failureCode: "session-creation-failed"; diagnostics?: never }
  | {
      failureCode: Exclude<ChildFailureCode, "session-creation-failed">;
      diagnostics: ChildFailureDiagnostics;
    };

/** Typed result of running one isolated child session. */
export type ChildRunOutcome<T> =
  | { kind: "success"; value: T; usage?: Usage }
  | ({ kind: "failed"; usage?: Usage } & ChildFailedResult)
  | { kind: "canceled"; diagnostics: ChildFailureDiagnostics; usage?: Usage }
  | { kind: "timeout"; timeoutMs: number; diagnostics: ChildFailureDiagnostics; usage?: Usage };

export interface ReviewProgress {
  turns: number;
  toolUses: number;
  toolErrors?: number;
  tokens?: {
    input: number;
    output: number;
    total: number;
    cacheRead?: number;
    cacheWrite?: number;
  };
}

export interface PlannerInvocation {
  prompt: string;
  /** Requested level for this Planner Draft; omitted values keep the package default. */
  requestedThinkingLevel?: ReviewThinkingLevel;
  providerAuthority?: AgentRunProviderAuthority;
  // biome-ignore lint/suspicious/noExplicitAny: Model<any> is Pi's canonical type
  model: Model<any>;
  cwd: string;
  signal?: AbortSignal;
  onProgress?: (progress: ReviewProgress) => void;
}

export type PlannerRunResult = ChildRunOutcome<PlannerDraft>;

/** Parent-facing execution provenance for an unavailable Reviewer Extension Set capability. */
export interface ReviewerCapabilityWarning {
  message: string;
}

export interface ReviewerAuditRequest {
  store: LocalReviewAuditStore;
  workspaceReceipt: ReviewWorkspaceReceipt;
}

export interface ReviewerInvocation {
  prompt: string;
  /** Requested level for this Reviewer Session; omitted values keep the package default. */
  requestedThinkingLevel?: ReviewThinkingLevel;
  providerAuthority?: AgentRunProviderAuthority;
  packetHash: string;
  task: ReviewTask;
  model: ReviewModelSelection;
  /** Optional explicit second model for Submission Recovery. */
  recoveryModel?: ReviewModelSelection;
  /** Requested recovery model id when configuration did not resolve. */
  recoveryModelId?: string;
  cwd: string;
  snapshot: ReviewSnapshot;
  audit?: ReviewerAuditRequest;
  /** A parent-owned bootstrap was configured, so reviewers must not bootstrap independently. */
  dependencyBootstrapConfigured?: boolean;
  signal?: AbortSignal;
  projectTrusted?: boolean;
  onProgress?: (progress: ReviewProgress) => void;
}

export type ReviewerExtensionSetStatus = "active" | "degraded" | "unobserved";

export type ReviewerRunResult = ChildRunOutcome<ReviewSubmission> & {
  modelId: string;
  requestedThinkingLevel: ReviewThinkingLevel;
  effectiveThinkingLevel: ModelThinkingLevel;
  reviewerExtensionSetStatus: ReviewerExtensionSetStatus;
  capabilityWarnings?: ReviewerCapabilityWarning[];
  audit?: ReviewAuditReference;
  submissionRecovery?: SubmissionRecovery;
};

interface ReviewTaskResultIdentity {
  taskId: string;
  mode: ReviewMode;
  modelId: string;
  /** Requested Reviewer Thinking Level for this task. */
  requestedThinkingLevel: ReviewThinkingLevel;
  /** Effective Reviewer Thinking Level after model capability clamping. */
  effectiveThinkingLevel: ModelThinkingLevel;
  /** SHA-256 of the exact reviewer packet bytes. */
  packetHash: string;
  /** Aggregate nested-model usage for this task, when reported by the provider. */
  usage?: Usage;
  /** Reviewer Extension Set capability degradation, kept separate from findings. */
  capabilityWarnings?: ReviewerCapabilityWarning[];
  /** Provenance for a Submission Recovery chain, when one started. */
  submissionRecovery?: SubmissionRecovery;
  /** Local-only opt-in reviewer replay, never included inline in review output. */
  audit?: ReviewAuditReference;
}

export type ReviewTaskResult = ReviewTaskResultIdentity &
  (
    | {
        status: "completed";
        verdict: TaskVerdict;
        findingCounts: FindingCounts;
        summary: string;
        findings: ReviewFinding[];
        criteriaCoverage: CriteriaCoverage;
      }
    | {
        status: "failed";
        failureCode: ChildFailureCode;
        diagnostics?: ChildFailureDiagnostics;
      }
    | {
        status: "canceled";
        diagnostics: ChildFailureDiagnostics;
      }
    | {
        status: "timeout";
        timeoutMs: number;
        diagnostics: ChildFailureDiagnostics;
      }
  );

/** Metadata for a transient Planner Draft offered by an interactive Review. */
export interface PlanningRecord {
  promptVersion: string;
  modelId: string;
  /** Planner usage is included with the final interactive Review result. */
  usage?: Usage;
  draft: PlannerDraft;
}

/** Retrieval metadata for a bounded parent-facing review output page. */
export interface ReviewOutputReference {
  artifactId: string;
  offset: number;
  nextOffset?: number;
  totalCharacters: number;
}

export interface ReviewBatchDetails {
  kind: "review-batch";
  provenance: "caller-supplied" | "planner-assisted";
  snapshot: ReviewSnapshotSummary;
  review: ReviewInput;
  /** Optional path focus validated against the frozen after state. */
  scope?: ReviewScope;
  /** Verification receipt for the shared frozen Review Workspace. */
  workspaceReceipt: ReviewWorkspaceReceipt;
  planning?: PlanningRecord;
  results: ReviewTaskResult[];
  cleanupWarning?: ReviewWorkspaceCleanupWarning;
  output?: ReviewOutputReference;
}

export interface ReviewPacket {
  prompt: string;
  /** SHA-256 of prompt encoded as UTF-8, used to verify adapter parity. */
  packetHash: string;
  taskId: string;
}
