import type { Model, Usage } from "@earendil-works/pi-ai";
import type { ChildLifecycleTrace } from "./tool/child-lifecycle-trace.ts";

/** A 7-64 character hexadecimal Git commit id, pinned to its full object id during resolution. */
export type CommitId = string;

/** The Git change selected for review. */
export type ReviewTargetSpec =
  | { kind: "working-tree" }
  | { kind: "comparison"; baseCommit: CommitId }
  | { kind: "commit"; commit: CommitId };

/** Resolved identity of a selected review target. */
export type ResolvedReviewTarget =
  | { kind: "working-tree"; headCommit: CommitId }
  | {
      kind: "comparison";
      requestedBaseCommit: CommitId;
      mergeBaseCommit: CommitId;
      headCommit: CommitId;
    }
  | { kind: "commit"; commit: CommitId; parentCommit?: CommitId };

export interface DiffStats {
  files: number;
  additions: number;
  deletions: number;
}

/** Concrete target metadata and diff identity resolved before reviewer execution. */
export interface ReviewSnapshot {
  /** Canonical worktree root retained only inside the Review Engine. */
  repositoryRoot: string;
  requestedTarget: ReviewTargetSpec;
  target: ResolvedReviewTarget;
  title: string;
  changedFiles: string[];
  /** SHA-256 of the exact canonical target patch bytes. */
  diffHash: string;
  stats: DiffStats;
}

export type ReviewSnapshotSummary = Omit<ReviewSnapshot, "repositoryRoot">;

/** One independent caller-defined review objective. */
export interface ReviewTask {
  id: string;
  instructions: string;
}

/** Semantic input shared with the reviewer tasks in one run. */
export interface ReviewInput {
  sharedContext?: string;
  tasks: ReviewTask[];
}

/** Advisory review input generated by the optional lightweight Planner. */
export type PlannerDraft = ReviewInput;

export type FindingImpact = "low" | "medium" | "high";
export type FindingEffort = "small" | "medium" | "large";
export type TaskVerdict = "pass" | "issues";

export interface ReviewLocation {
  path: string;
  startLine: number;
  endLine: number;
}

/** One structured issue submitted by a reviewer task. */
export interface ReviewFinding {
  title: string;
  description: string;
  blocksAcceptance: boolean;
  impact: FindingImpact;
  effort: FindingEffort;
  confidence: number;
  location?: ReviewLocation;
}

/** Fixed Review Engine-owned submission grammar. */
export interface ReviewSubmission {
  summary: string;
  findings: ReviewFinding[];
}

export interface NormalizedReviewSubmission extends ReviewSubmission {
  verdict: TaskVerdict;
}

export type ReviewModelSelection = import("@mrclrchtr/supi-core/model-selection").ModelSelection;

export type ChildStage = "planner" | "reviewer";

export type ChildFailureCode =
  | "session-creation-failed"
  | "prompt-rejected"
  | "missing-structured-output"
  | "unexpected-runner-failure";

export interface ChildFailureDiagnostics {
  lifecycleTrace: ChildLifecycleTrace;
  turns: number;
  toolUses: number;
  tokens?: {
    input: number;
    output: number;
    total: number;
    cacheRead?: number;
    cacheWrite?: number;
  };
  recentActivity?: string[];
  lastAssistantStopReason?: string;
  lastAssistantToolCalls?: string[];
  /** Bounded, redacted canonical provider error from the last errored assistant message. */
  lastAssistantErrorText?: string;
  /** Bounded, redacted provider error from the most recent recovery lifecycle event. */
  lastLifecycleErrorText?: string;
}

export type ChildFailedResult =
  | { failureCode: "session-creation-failed"; diagnostics?: never }
  | {
      failureCode: Exclude<ChildFailureCode, "session-creation-failed">;
      diagnostics: ChildFailureDiagnostics;
    };

export interface ReviewProgress {
  turns: number;
  toolUses: number;
  tokens?: {
    input: number;
    output: number;
    total: number;
    cacheRead?: number;
    cacheWrite?: number;
  };
}

export interface PlannerInvocation {
  prompt: string;
  // biome-ignore lint/suspicious/noExplicitAny: Model<any> is Pi's canonical type
  model: Model<any>;
  cwd: string;
  signal?: AbortSignal;
  onProgress?: (progress: ReviewProgress) => void;
}

export type PlannerRunResult =
  | { kind: "success"; draft: PlannerDraft; usage?: Usage }
  | ({ kind: "failed"; usage?: Usage } & ChildFailedResult)
  | { kind: "canceled"; diagnostics: ChildFailureDiagnostics; usage?: Usage }
  | { kind: "timeout"; timeoutMs: number; diagnostics: ChildFailureDiagnostics; usage?: Usage };

export interface ReviewerInvocation {
  prompt: string;
  task: ReviewTask;
  model: ReviewModelSelection;
  cwd: string;
  snapshot: ReviewSnapshot;
  signal?: AbortSignal;
  onProgress?: (progress: ReviewProgress) => void;
}

export type ReviewerRunResult =
  | { kind: "success"; submission: ReviewSubmission; modelId: string; usage?: Usage }
  | ({ kind: "failed"; modelId: string; usage?: Usage } & ChildFailedResult)
  | { kind: "canceled"; modelId: string; diagnostics: ChildFailureDiagnostics; usage?: Usage }
  | {
      kind: "timeout";
      timeoutMs: number;
      modelId: string;
      diagnostics: ChildFailureDiagnostics;
      usage?: Usage;
    };

interface ReviewTaskResultIdentity {
  taskId: string;
  modelId: string;
  /** SHA-256 of the exact reviewer packet bytes. */
  packetHash: string;
  /** Aggregate nested-model usage for this task, when reported by the provider. */
  usage?: Usage;
}

export type ReviewTaskResult = ReviewTaskResultIdentity &
  (
    | {
        status: "completed";
        verdict: TaskVerdict;
        summary: string;
        findings: ReviewFinding[];
      }
    | {
        status: "failed";
        failureCode: ChildFailureCode;
        diagnostics?: ChildFailureDiagnostics;
      }
    | {
        status: "canceled";
        diagnostics: ChildFailureDiagnostics;
      }
    | {
        status: "timeout";
        timeoutMs: number;
        diagnostics: ChildFailureDiagnostics;
      }
  );

export interface PlanningRecord {
  promptVersion: string;
  modelId: string;
  /** Planner usage is informational here and is not charged again by the run tool. */
  usage?: Usage;
  draft: PlannerDraft;
  effectiveReview: ReviewInput;
  decision: "accept-draft" | "use-review";
}

/** Retrieval metadata for a bounded parent-facing review output page. */
export interface ReviewOutputReference {
  artifactId: string;
  offset: number;
  nextOffset?: number;
  totalCharacters: number;
}

export interface ReviewBatchDetails {
  kind: "review-batch";
  mode: "direct" | "prepared";
  provenance: "caller-supplied" | "planner-assisted";
  snapshot: ReviewSnapshotSummary;
  review: ReviewInput;
  planning?: PlanningRecord;
  results: ReviewTaskResult[];
  output?: ReviewOutputReference;
}

export interface PreparedReviewDetails {
  kind: "review-prepared";
  planId: string;
  snapshot: ReviewSnapshotSummary;
  reviewerModelId: string;
  plannerDraft?: PlannerDraft;
  plannerModelId?: string;
  plannerPromptVersion?: string;
  plannerUsage?: Usage;
  plannerFailure?: Exclude<PlannerRunResult, { kind: "success" }>;
  output?: ReviewOutputReference;
}

export interface ReviewPacket {
  prompt: string;
  /** SHA-256 of prompt encoded as UTF-8, used to verify adapter parity. */
  packetHash: string;
  taskId: string;
}
