/**
 * Terminal tab title spinner for pi.
 *
 * Patches `ctx.ui.setTitle` so it remembers whatever title pi (or another
 * extension) last set. While the agent is working (`agent_start` → `agent_end`)
 * it prepends an animated spinner frame; when idle it restores the exact title.
 */
import type { ExtensionAPI, ExtensionContext } from "@mariozechner/pi-coding-agent";

const SPINNER_FRAMES = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"];
const FALLBACK_TITLE = "pi";

/** Check whether a title was generated by this spinner (prevents double-prefixing). */
function isSpinnerTitle(title: string): boolean {
  return SPINNER_FRAMES.some((f) => title.startsWith(`${f} `));
}

/**
 * Intercept `ctx.ui.setTitle` to track the "base" title set by pi or other
 * extensions. While spinning, external calls only update the stored base;
 * the interval renders the actual tab text on the next tick.
 */
function patchSetTitle(
  ctx: ExtensionContext,
  state: { baseTitle: string; timer: ReturnType<typeof setInterval> | null; patched: boolean },
) {
  if (state.patched) return;
  const ui = ctx.ui;
  const orig = ui.setTitle.bind(ui);
  ui.setTitle = (title: string) => {
    if (!isSpinnerTitle(title)) {
      state.baseTitle = title || FALLBACK_TITLE;
      // While spinning, only update the stored base title;
      // the interval will render it with the spinner on the next tick.
      if (!state.timer) {
        orig(state.baseTitle);
      }
    } else {
      orig(title);
    }
  };
  state.patched = true;
}

/** Start the spinner interval, cycling through frames every 80ms. */
function startSpinner(
  ctx: ExtensionContext,
  state: { baseTitle: string; timer: ReturnType<typeof setInterval> | null; frame: number },
) {
  if (state.timer) clearInterval(state.timer);
  state.timer = setInterval(() => {
    const icon = SPINNER_FRAMES[state.frame % SPINNER_FRAMES.length];
    ctx.ui.setTitle(`${icon} ${state.baseTitle}`);
    state.frame++;
  }, 80);
}

/** Stop the spinner and restore the base title. */
function stopSpinner(
  ctx: ExtensionContext,
  state: { baseTitle: string; timer: ReturnType<typeof setInterval> | null; frame: number },
) {
  if (state.timer) {
    clearInterval(state.timer);
    state.timer = null;
  }
  state.frame = 0;
  ctx.ui.setTitle(state.baseTitle);
}

export default function tabSpinner(pi: ExtensionAPI) {
  const state = {
    baseTitle: FALLBACK_TITLE,
    timer: null as ReturnType<typeof setInterval> | null,
    frame: 0,
    patched: false,
  };

  pi.on("session_start", async (_event, ctx) => {
    patchSetTitle(ctx, state);
  });

  pi.on("agent_start", async (_event, ctx) => {
    startSpinner(ctx, state);
  });

  pi.on("agent_end", async (_event, ctx) => {
    stopSpinner(ctx, state);
  });

  pi.on("session_shutdown", async (_event, ctx) => {
    if (state.timer) {
      clearInterval(state.timer);
      state.timer = null;
    }
    state.frame = 0;
    // Best-effort restore so the spinner doesn't stick in the tab title
    ctx.ui.setTitle(state.baseTitle);
  });
}
